#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 25 13:32:50 COT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1.zip
enableShaders=true
