#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 26 10:07:57 COT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1.zip
enableShaders=true
