#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 24 14:32:04 COT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.0.zip
enableShaders=true
